kxh: fix prewarm auto-kill on detach

diff --git a/.local/bin/_kxh_prewarm b/.local/bin/_kxh_prewarm
--- a/.local/bin/_kxh_prewarm
+++ b/.local/bin/_kxh_prewarm
@@ -3,66 +3,49 @@
 # so that new shell sessions can be spawned quickly.
 # This script has been adapted from:
 # https://github.com/anki-code/xonsh-prewarmed
-_screen_prewarm() {
-    if ! command -v screen &> /dev/null; then
-        if [[ -z "$@" ]]; then
-            exec $SHELL
-        else
-            exec "$@"
-        fi
-    fi
-    PREFIX="__prewarmer_$(echo "$@" | md5sum | head -c 8)"
+PREFIX="prewarm_$(echo "$@" | md5sum | head -c 8)"
 
-    get_reserve_sess_id() {
-        screen -ls | \
-            grep -E "${PREFIX}_reserve.*Detached" | \
-            awk -F '[.]|\t' '/[0-9]+\./{print $2}' | \
-            tail -n 1
-    }
-
-    reserve_sess_id=$(get_reserve_sess_id)
-    if [[ -z "$reserve_sess_id" ]]; then
-        screen -S "${PREFIX}_reserve" -d -m "$@"
-        reserve_sess_id=$(get_reserve_sess_id)
-    fi
-    screen -S "${PREFIX}_reserve" -d -m "$@"
-    screen -S "$reserve_sess_id" -X sessionname "${PREFIX}_active"
-    screen -d -r "$reserve_sess_id"
+_tmux() {
+    $KXH_PREWARMER -L __kxh_prewarm -f /dev/null "$@"
 }
-
+_tmux_detached_sessions() {
+    _tmux ls -f '#{==:#{session_attached},0}' 2>/dev/null | \
+        grep -E "${PREFIX}_(\d+)_$1" | cut -d ':' -f 1
+}
+_tmux_invalidate() {
+    local sessions=$(_tmux_detached_sessions "reserve")
+    for sess in $sessions; do
+        _tmux kill-session -t "$sess"
+    done
+}
 _tmux_prewarm() {
     if ! command -v tmux &> /dev/null; then
+        echo "tmux is not found, not prewarmed" >&2
+        echo "Press Enter to continue" >&2
+        read -r
         if [[ -z "$@" ]]; then
             exec $SHELL
         else
             exec "$@"
         fi
     fi
-    PREFIX="prewarm_$(echo "$@" | md5sum | head -c 8)"
-    _tmux() {
-        tmux -L __kxh_prewarm -f /dev/null "$@"
-    }
     _rand() {
         shuf -i 0-100000 -n 1
     }
-    get_sessions() {
-        _tmux ls -f '#{==:#{session_attached},0}' 2>/dev/null | \
-            grep "${PREFIX}_$1" | cut -d ':' -f 1
-    }
-    local orphan_sessions=$(get_sessions "active")
-    for sess in $orphan_sessions; do
-        _tmux kill-session -t "$sess"
-    done
-    local reserve_sessions=$(get_sessions "reserve")
+    local reserve_sessions=$(_tmux_detached_sessions "reserve")
     local reserve_sess_id=$(echo $reserve_sessions | cut -d ' ' -f 1)
     if [[ -z "$reserve_sess_id" ]]; then
         local rand=$(_rand)
-        reserve_sess_id="${PREFIX}_reserve_${rand}"
+        reserve_sess_id="${PREFIX}_${rand}_reserve"
+        local env_vars=(
+            TERM SSH_AUTH_SOCK SSH_CONNECTION
+            KITTY_WINDOW_ID KITTY_PUBLIC_KEY KXH_COLOR_MODE)
         _tmux new-session -s "$reserve_sess_id" -d "$@" \
-            \; set -g update-environment "TERM SSH_AUTH_SOCK SSH_CONNECTION KXH_COLOR_MODE KITTY_WINDOW_ID KITTY_PUBLIC_KEY" \
+            \; set -g update-environment "${env_vars[*]}" \
             \; set -g default-terminal '$TERM' \
-            \; set -g @kxh_prewarm 1 \
-            \; set-option -g mouse on \
+            \; set -g mouse on \
+            \; set -g prefix None \
+            \; set -g prefix2 None \
             \; set -g status off \
             \; set -g set-titles on \
             \; set -g set-titles-string "#T" \
@@ -72,16 +55,22 @@ _tmux_prewarm() {
     local active_sess_id=$(echo $reserve_sess_id | sed "s/_reserve/_active/")
     local num_reserved_sessions=$(echo $reserve_sessions | wc -w)
     if [[ $num_reserved_sessions -le 1 ]]; then
-        _tmux new-session -s "${PREFIX}_reserve_${rand}" -d "$@"
+        _tmux new-session -s "${PREFIX}_${rand}_reserve" -d "$@"
     fi
     _tmux rename-session -t "$reserve_sess_id" "$active_sess_id"
     _tmux attach-session -t "$active_sess_id" \
+        \; set @kxh_prewarm_id "$active_sess_id" \
         \; set-hook -t "$active_sess_id" client-detached \
-            "kill-session -t $active_sess_id"
+            "if -F '#{==:#{session_attached},0}' 'kill-session -t $active_sess_id'"
 }
 
-if [[ $KXH_PREWARM_MODE == "screen" ]]; then
-    _screen_prewarm "$@"
-else
+if [[ $KXH_PREWARMER == "invalidate" ]]; then
+    _tmux_invalidate
+fi
+if [[ $KXH_PREWARMER == "tmux" ]]; then
     _tmux_prewarm "$@"
+elif [[ -z "$@" ]]; then
+    exec $SHELL
+else
+    exec "$@"
 fi
