Misc

diff --git a/.local/bin/hfd b/.local/bin/hfd
--- a/.local/bin/hfd
+++ b/.local/bin/hfd
@@ -10,25 +10,26 @@ trap 'printf "${YELLOW}\nDownload interrupted. If you re-run the command, you ca
 display_help() {
     cat << EOF
 Usage:
-  hfd <model_id> [--include include_pattern] [--exclude exclude_pattern] [--hf_username username] [--hf_token token] [--tool wget|aria2c] [-x threads] [--dataset]
+  hfd <repo_id> [--include include_pattern1 include_pattern2 ...] [--exclude exclude_pattern1 exclude_pattern2 ...] [--hf_username username] [--hf_token token] [--tool aria2c|wget] [-x threads] [--dataset] [--local-dir path]
 
 Description:
-  Downloads a model or dataset from Hugging Face using the provided model ID.
+  Downloads a model or dataset from Hugging Face using the provided repo ID.
 
 Parameters:
-  model_id        The Hugging Face model ID in the format 'repo/model_name'.
-  --include       (Optional) Flag to specify a string pattern to include files for downloading.
-  --exclude       (Optional) Flag to specify a string pattern to exclude files from downloading.
-  exclude_pattern The pattern to match against filenames for exclusion.
-  --hf_username   (Optional) Hugging Face username for authentication.
+  repo_id        The Hugging Face repo ID in the format 'org/repo_name'.
+  --include       (Optional) Flag to specify string patterns to include files for downloading. Supports multiple patterns.
+  --exclude       (Optional) Flag to specify string patterns to exclude files from downloading. Supports multiple patterns.
+  include/exclude_pattern The patterns to match against filenames, supports wildcard characters. e.g., '--exclude *.safetensor *.txt', '--include vae/*'.
+  --hf_username   (Optional) Hugging Face username for authentication. **NOT EMAIL**.
   --hf_token      (Optional) Hugging Face token for authentication.
-  --tool          (Optional) Download tool to use. Can be wget (default) or aria2c.
-  -x              (Optional) Number of download threads for aria2c.
+  --tool          (Optional) Download tool to use. Can be aria2c (default) or wget.
+  -x              (Optional) Number of download threads for aria2c. Defaults to 4.
   --dataset       (Optional) Flag to indicate downloading a dataset.
+  --local-dir     (Optional) Local directory path where the model or dataset will be stored.
 
 Example:
-  hfd bigscience/bloom-560m --exclude safetensors
-  hfd meta-llama/Llama-2-7b --hf_username myuser --hf_token mytoken --tool aria2c -x 8
+  hfd bigscience/bloom-560m --exclude *.safetensors
+  hfd meta-llama/Llama-2-7b --hf_username myuser --hf_token mytoken -x 4
   hfd lavita/medical-qa-shared-task-v1-toy --dataset
 EOF
     exit 1
@@ -38,19 +39,35 @@ MODEL_ID=$1
 shift
 
 # Default values
-TOOL="wget"
-THREADS=1
+TOOL="aria2c"
+THREADS=4
 HF_ENDPOINT=${HF_ENDPOINT:-"https://huggingface.co"}
+
+INCLUDE_PATTERNS=()
+EXCLUDE_PATTERNS=()
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        --include) INCLUDE_PATTERN="$2"; shift 2 ;;
-        --exclude) EXCLUDE_PATTERN="$2"; shift 2 ;;
+        --include)
+            shift
+            while [[ $# -gt 0 && ! $1 =~ ^-- ]]; do
+                INCLUDE_PATTERNS+=("$1")
+                shift
+            done
+            ;;
+        --exclude)
+            shift
+            while [[ $# -gt 0 && ! $1 =~ ^-- ]]; do
+                EXCLUDE_PATTERNS+=("$1")
+                shift
+            done
+            ;;
         --hf_username) HF_USERNAME="$2"; shift 2 ;;
         --hf_token) HF_TOKEN="$2"; shift 2 ;;
         --tool) TOOL="$2"; shift 2 ;;
         -x) THREADS="$2"; shift 2 ;;
         --dataset) DATASET=1; shift ;;
+        --local-dir) LOCAL_DIR="$2"; shift 2 ;;
         *) shift ;;
     esac
 done
@@ -63,26 +80,36 @@ check_command() {
     fi
 }
 
+# Mark current repo safe when using shared file system like samba or nfs
+ensure_ownership() {
+    if git status 2>&1 | grep "fatal: detected dubious ownership in repository at" > /dev/null; then
+        git config --global --add safe.directory "${PWD}"
+        printf "${YELLOW}Detected dubious ownership in repository, mark ${PWD} safe using git, edit ~/.gitconfig if you want to reverse this.\n${NC}"
+    fi
+}
+
 [[ "$TOOL" == "aria2c" ]] && check_command aria2c
 [[ "$TOOL" == "wget" ]] && check_command wget
 check_command curl; check_command git; check_command git-lfs
 
 [[ -z "$MODEL_ID" || "$MODEL_ID" =~ ^-h ]] && display_help
 
-MODEL_DIR="${MODEL_ID#*/}"
+if [[ -z "$LOCAL_DIR" ]]; then
+    LOCAL_DIR="${MODEL_ID#*/}"
+fi
 
 if [[ "$DATASET" == 1 ]]; then
     MODEL_ID="datasets/$MODEL_ID"
 fi
-echo "Downloading to ./$MODEL_DIR"
+echo "Downloading to $LOCAL_DIR"
 
-if [ -d "$MODEL_DIR/.git" ]; then
-    printf "${YELLOW}%s exists, Skip Clone.\n${NC}" "$MODEL_DIR"
-    cd "$MODEL_DIR" && GIT_LFS_SKIP_SMUDGE=1 git pull || { printf "Git pull failed.\n"; exit 1; }
+if [ -d "$LOCAL_DIR/.git" ]; then
+    printf "${YELLOW}%s exists, Skip Clone.\n${NC}" "$LOCAL_DIR"
+    cd "$LOCAL_DIR" && ensure_ownership && GIT_LFS_SKIP_SMUDGE=1 git pull || { printf "${RED}Git pull failed.${NC}\n"; exit 1; }
 else
     REPO_URL="$HF_ENDPOINT/$MODEL_ID"
     GIT_REFS_URL="${REPO_URL}/info/refs?service=git-upload-pack"
-    echo "Test GIT_REFS_URL: $GIT_REFS_URL"
+    echo "Testing GIT_REFS_URL: $GIT_REFS_URL"
     response=$(curl -s -o /dev/null -w "%{http_code}" "$GIT_REFS_URL")
     if [ "$response" == "401" ] || [ "$response" == "403" ]; then
         if [[ -z "$HF_USERNAME" || -z "$HF_TOKEN" ]]; then
@@ -91,21 +118,46 @@ else
         fi
         REPO_URL="https://$HF_USERNAME:$HF_TOKEN@${HF_ENDPOINT#https://}/$MODEL_ID"
     elif [ "$response" != "200" ]; then
-        echo -e "${RED}Unexpected HTTP Status Code: $response.\nExiting.\n${NC}"; exit 1
+        printf "${RED}Unexpected HTTP Status Code: $response\n${NC}"
+        printf "${YELLOW}Executing debug command: curl -v %s\nOutput:${NC}\n" "$GIT_REFS_URL"
+        curl -v "$GIT_REFS_URL"; printf "\n${RED}Git clone failed.\n${NC}"; exit 1
     fi
-    echo "git clone $REPO_URL"
+    echo "GIT_LFS_SKIP_SMUDGE=1 git clone $REPO_URL $LOCAL_DIR"
 
-    GIT_LFS_SKIP_SMUDGE=1 git clone "$REPO_URL" && cd "$MODEL_DIR" || { printf "${RED}Git clone failed.\n${NC}"; exit 1; }
-    for file in $(git lfs ls-files | awk '{print $3}'); do
+    GIT_LFS_SKIP_SMUDGE=1 git clone $REPO_URL $LOCAL_DIR && cd "$LOCAL_DIR" || { printf "${RED}Git clone failed.\n${NC}"; exit 1; }
+
+    ensure_ownership
+
+    while IFS= read -r file; do
         truncate -s 0 "$file"
-    done
+    done <<< $(git lfs ls-files | cut -d ' ' -f 3-)
 fi
 
-printf "\nStart Downloading lfs files, bash script:\n"
-files=$(git lfs ls-files | awk '{print $3}')
+printf "\nStart Downloading lfs files, bash script:\ncd $LOCAL_DIR\n"
+files=$(git lfs ls-files | cut -d ' ' -f 3-)
 declare -a urls
 
-for file in $files; do
+file_matches_include_patterns() {
+    local file="$1"
+    for pattern in "${INCLUDE_PATTERNS[@]}"; do
+        if [[ "$file" == $pattern ]]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+file_matches_exclude_patterns() {
+    local file="$1"
+    for pattern in "${EXCLUDE_PATTERNS[@]}"; do
+        if [[ "$file" == $pattern ]]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+while IFS= read -r file; do
     url="$HF_ENDPOINT/$MODEL_ID/resolve/main/$file"
     file_dir=$(dirname "$file")
     mkdir -p "$file_dir"
@@ -113,22 +165,30 @@ for file in $files; do
         download_cmd="wget -c \"$url\" -O \"$file\""
         [[ -n "$HF_TOKEN" ]] && download_cmd="wget --header=\"Authorization: Bearer ${HF_TOKEN}\" -c \"$url\" -O \"$file\""
     else
-        download_cmd="aria2c -x $THREADS -s $THREADS -k 1M -c \"$url\" -d \"$file_dir\" -o \"$(basename "$file")\""
-        [[ -n "$HF_TOKEN" ]] && download_cmd="aria2c --header=\"Authorization: Bearer ${HF_TOKEN}\" -x $THREADS -s $THREADS -k 1M -c \"$url\" -d \"$file_dir\" -o \"$(basename "$file")\""
+        download_cmd="aria2c --console-log-level=error --file-allocation=none -x $THREADS -s $THREADS -k 1M -c \"$url\" -d \"$file_dir\" -o \"$(basename "$file")\""
+        [[ -n "$HF_TOKEN" ]] && download_cmd="aria2c --header=\"Authorization: Bearer ${HF_TOKEN}\" --console-log-level=error --file-allocation=none -x $THREADS -s $THREADS -k 1M -c \"$url\" -d \"$file_dir\" -o \"$(basename "$file")\""
     fi
-    [[ -n "$INCLUDE_PATTERN" && $file != *"$INCLUDE_PATTERN"* ]] && printf "# %s\n" "$download_cmd" && continue
-    [[ -n "$EXCLUDE_PATTERN" && $file == *"$EXCLUDE_PATTERN"* ]] && printf "# %s\n" "$download_cmd" && continue
+
+    if [[ ${#INCLUDE_PATTERNS[@]} -gt 0 ]]; then
+        file_matches_include_patterns "$file" || { printf "# %s\n" "$download_cmd"; continue; }
+    fi
+
+    if [[ ${#EXCLUDE_PATTERNS[@]} -gt 0 ]]; then
+        file_matches_exclude_patterns "$file" && { printf "# %s\n" "$download_cmd"; continue; }
+    fi
+
     printf "%s\n" "$download_cmd"
     urls+=("$url|$file")
-done
+done <<< "$files"
 
 for url_file in "${urls[@]}"; do
     IFS='|' read -r url file <<< "$url_file"
+    printf "${YELLOW}Start downloading ${file}.\n${NC}"
     file_dir=$(dirname "$file")
     if [[ "$TOOL" == "wget" ]]; then
         [[ -n "$HF_TOKEN" ]] && wget --header="Authorization: Bearer ${HF_TOKEN}" -c "$url" -O "$file" || wget -c "$url" -O "$file"
     else
-        [[ -n "$HF_TOKEN" ]] && aria2c --header="Authorization: Bearer ${HF_TOKEN}" -x $THREADS -s $THREADS -k 1M -c "$url" -d "$file_dir" -o "$(basename "$file")" || aria2c -x $THREADS -s $THREADS -k 1M -c "$url" -d "$file_dir" -o "$(basename "$file")"
+        [[ -n "$HF_TOKEN" ]] && aria2c --header="Authorization: Bearer ${HF_TOKEN}" --console-log-level=error --file-allocation=none -x $THREADS -s $THREADS -k 1M -c "$url" -d "$file_dir" -o "$(basename "$file")" || aria2c --console-log-level=error --file-allocation=none -x $THREADS -s $THREADS -k 1M -c "$url" -d "$file_dir" -o "$(basename "$file")"
     fi
     [[ $? -eq 0 ]] && printf "Downloaded %s successfully.\n" "$url" || { printf "${RED}Failed to download %s.\n${NC}" "$url"; exit 1; }
 done
